;Morroblivion INI configuration
;==============================
;The following INI file allows you to configure some aspects of Morroblivion mod.


;========Quest Markers=========
;Enable or disable quest markers (arrow pointers on map) for Morrowind quests.
;1 - enabled (default)
;0 - disabled

set MorroDefaultQuest.QuestMarkersEnabled to 1


;==========Fast Travel=========
;Enable or disable map-based fast travel for Morrowind world.
;1 - enabled (default)
;0 - disabled

set MorroDefaultQuest.FastTravelEnabled to 1


;====== Hardcore Harvest ======
;The following setting enable or disable harvest restrictions.
;1 - enabled
;0 - disabled (default)

set MorroDefaultQuest.HardcoreHarvestMuck to 0
;Enables or disables requirement of muck shovel to harvest muck.

set MorroDefaultQuest.HardcoreHarvestOre to 0
;Enables or disables requirement of pickaxe to harvest ore.


;========== Taunting ==========
;Enables or disables the ability to taunt NPCs in dialogue.
;Could be useful during several quests, when you need to kill normally unaggressive NPCs.
;Disable if you want to use other mod with similar functionality (Persuation Overhaul, for example), or if you simply don't want this feature.
;1 - enabled (default)
;0 - disabled

set MorroDefaultQuest.TauntEnabled to 1


;====Ingame Error Detection====
;Enables or disables automatic ingame detection of the most common Morroblivion installation errors.
;Disable only if you're an experienced mod user.
;1 - enabled (default)
;0 - disabled

set MorroDefaultQuest.ErrorDetection to 1


;======Alternative Start=======
;This setting toggles the use of Morroblivion's alternative start.
;When enabled, starting a new game from Oblivion main menu will start in Morrowind. When disabled you'll get a normal Oblivion new game.
;1 - enabled (default)
;0 - disabled

set mwMainMenu.AltStart to 1

;======Used in Dagger Galore======
; Enable all Strict Morrowind Behavior settings
set mwFixes.StrictMWAll to 0 
;
; To Do (not implemented): Enable Strict Morrowind Argonian Waterbreathing behavior
set mwFixes.StrictMWWaterBreathing to 0
;
; Enable Strict Morrowind Starting Spell List (removes the two default Oblivion spells)
set mwFixes.StrictMWSpells to 0
;
; Enable Strict Morrowind Run/Walking Behavior (affects speed and athletics)
set mwFixes.StrictMWRunSpeed to 0
;
; Enable Strict Morrowind Fatigue Drain Behavior (running drains fatigue, fatigue regenerates much more slowly)
set mwFixes.StrictMWFatigueDrain to 0
;
; To Do (not implemented): Enable Strict Morrowind Encumbrance Slowing
set mwFixes.StrictMWEncumbranceSlowing to 0
;
; Enable Morrowind-style Enchantment Selection
set mwFixes.StrictMWEnchantmentSelection to 0

;======More-Armor-Slots======
; Enable/Disable Morroblivion Clothing-Armor Slots (requires more-armor-slots mod)
set mwFixes.ClothingAndArmorMode to 0
;
; Enable/Disable Beast Race Restrictions (requires more-armor slots)
set mwFixes.EnableRaceRestrictions to 0
;
;Enable/Disable multiple pieces of armor (requires more-armor slots)
set mwFixes.EnableMoreArmorSlots to 0