; ================================================
; MorroblivionLeviation.ini
;
; Version: 0.1
; Author: Eazzy
; ================================================
; 
; Edit this file to customize Morroblivion Levitation to your preferences.
; Place this file in your "Oblivion\Data\Ini" folder.
;
; ------------------------------------------------
; Settings
; ------------------------------------------------
;
; Acceleration base factor
; This setting determines how fast you are accelerating when you press and hold any movement control keys (Forward/Back/Left/Right) while levitating.
; Higher values let you accelerate faster and also raise your maximum levitation velocity. 
set JDLevitationData.accBaseFact to 1.0		 ;default: 1.0	

; Acceleration mod factors
; These factors are applied to accBaseFact when using the weak, strong and wild levitation respectively.
set JDLevitationData.accWeakFact to 0.5		 ;default: 0.5	
set JDLevitationData.accStrongFact to 2.0	 ;default: 2.0
set JDLevitationData.accWildFact to 4.0		 ;default: 4.0

; Damping base factor
; This setting determines how fast your velocity drops when you release your movement control keys.
; Higher values let your velocity drop faster, but also lower your maximum levitation velocity.
set JDLevitationData.dampBaseFact to 1.0	 ;default: 1.0	

; Test mode
; When set to 1 four Levitation testspells (Weak, Normal, Strong and Wild Levitation) will be added to your inventory when loading this mod for the first time.
; All testspells are novice level and cost no magicka
set JDLevitationStartup.testMode to 0







